import type { Metadata } from 'next';
import EmotionRegistry from '@/components/ThemeRegistry/Registry';
import React from 'react';

export const metadata: Metadata = {
  title: 'Cuculus Roadmap',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <EmotionRegistry>{children}</EmotionRegistry>
      </body>
    </html>
  );
}
