name: Run VRT

on:
  pull_request:
    branches: [ main ]

jobs:
  run-vrt:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment:
      name: develop
    env:
      REG_SUITE_CLIENT_ID: ${{ secrets.REG_SUITE_CLIENT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REG_SUITE_S3_BUCKET_NAME: ${{ secrets.REG_SUITE_S3_BUCKET_NAME }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get node version from volta
        id: get-node-version
        uses: keita-hino/get-node-version-from-volta@main

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.get-node-version.outputs.nodeVersion }}

      - name: NPM install
        run: npm install

      - name: run reg-suit
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npx reg-suit run
