on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get node version from volta
        id: get-node-version
        uses: keita-hino/get-node-version-from-volta@main

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.get-node-

      - name: NPM install
        run: npm install

      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull

      - name: run reg-suit
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npx reg-suit run
